import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./globalIcons.css";
import NavigationBar from "@/components/Header/NavigationBar";
import Footer from "@/components/Footer/Index";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Estetica Automotriz Gerardo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <head></head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  bg-slate-50`}
      >
        <header>
          <NavigationBar />
        </header>

        <main className="">{children}</main>
        {/* {children} */}
        <Footer />
      </body>
    </html>
  );
}
